### ISSUE TITLE
question about avb 2.0

### ISSUE THREAD

**Issue by lxy0797** [sonyxperiadev/device-sony-sagami#13]
I heard [avb_custom_avb](https://github.com/sonyxperiadev/bug_tracker/issues/743#issue-1124869012) has accomplished on sagami.
  Does any one can confirm this news?

**Comment by Flex1911** [comment]
I don't know whether that would be a sufficient confirmation for you, but I have pdx215 (X1 III) running custom OS with locked bootloader:
<details>

![20220221_203244](https://user-images.githubusercontent.com/3727415/155006536-21a19ecb-b77b-43da-b28b-4d5a878ea027.jpeg)

</details>

**Comment by lxy0797** [comment]
> I don't know whether that would be a sufficient confirmation for you, but I have pdx215 (X1 III) running custom OS with locked bootloader:

Seems it is bricked. What's the OS?

**Comment by Flex1911** [comment]
> > I don't know whether that would be a sufficient confirmation for you, but I have pdx215 (X1 III) running custom OS with locked bootloader:
> 
> Seems it is bricked. What's the OS?

This is the usual warning you get when AVB 2.0 is in yellow state (detected the image that is not signed by default AVB key, but the custom root of trust set by `fastboot flash avb_custom_key`). The OS I'm running is just AOSP signed with my own keys.

**Comment by jerpelea** [comment]
please use the bug tracker
